/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as TickerRegistry from "../artifacts/TickerRegistry.json";
export const artifacts = { TickerRegistry: TickerRegistry as ContractArtifact };
